#!/usr/bin/python3
#text2="ADLNEXDOYLSFYQQBZEYFOQRLLAKLOWLLESSQBZOGVFQDLRYIWFOUTPIGQDSOKIUPSZIZJUMGARGGWGFLSPIFXCBDOSPBIAIZKLZTYAEXUGQAUDIHZHHNFUXQGLRHMFQZHTQGKZCSOSMHBCZSQHHGBLADGKUHLCFYUQAVDGPDUFLCAQSAGLEPISXIZIQYUEDYOVIWEQVRDIOQGUOHEVIWMTSPDZQLEFGTGWWEDQHFHLNFHHOCUTDSOQFSEEHLRTLRQRWQGYEEWRGFJEEHHEAHCTMQQGCIDXXQZSEEXHXZLSCYHXOWUUWVMBJEPIFMZJUXPHEHVCWEJQCBEZGRDSSEDIVQOBLQTUAXLTQWWBCYTQTDDZHFARGMHPOZSSQBZTMGNGBLODKDZWZAFMRZBVNOSPYSYCUEOQEBIMTRGFIUFHHBFVMAYYAWYLQTUAXLTATHZGAAOODUBZICYHPSWRAXHSSYEFHDURLRXIVPSCEXSSBSBREIWFCBTQPDOCTMGRDGHLOBIQEHHCWHHZCTBDIXESZEZXUQDYIEIVABARQNRUBALMJRZRHTUSQADLNEXDOYWADQLOSSLQWFUCURQXUAICEOEQABPCMPUQROAFWXESLNAZDZQLAFXFUGJOPIOXVWINQBMVVOAVDOZLODEQSSJLAYGIOATQQFHADADILZHLLOIVFIULAKLOWLLXMEDSKIEXUUPBEEIOABSEEXHDALSPIOMZPCQRFQOWAOLH"
def occ(text):
	alpha="ABCDEFGHIJKLMNOPQRSTUVWXYZ "
	c=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
	for i in text:
		c[alpha.index(i)]+=1
	return c
    
def dechiffrement(txt):
	alpha="ABCDEFGHIJKLMNOPQRSTUVWXYZ "
	alpha2="STUVWXYZABCDEFGHIJKLMNOPQR "
	clair=""
	for i in txt:
		clair+=alpha2[alpha.index(i)]
	return clair
    
def polyalphabitiqueaveccalculindicecoicidence(text):
	alpha="ABCDEFGHIJKLMNOPQRSTUVWXYZ "
	c=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
	for i in text:
		c[alpha.index(i)]+=1
	n=0
	for i in range(len(c)-1):
		n+=c[i]
	ic=0
	for i in range(len(c)-1):
		ic+=(c[i]*(c[i]-1))/(n*(n-1))
	return ic

def longeurdecle(text):
	text=text.replace(" ","")
	x=1
	while(True):
		nbchar=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
		for i in range(0,len(text),x):
			nbchar[alphabet.index(text[i])]+=1
		n=0
		for i in nbchar:
			n+=i
		s=0
		for i in range(len(nbchar)):
			s+=(nbchar[i]*(nbchar[i]-1))/(n*(n-1))
		if s>0.06:
			return s
		else:
			s+=1
def cryptanalyse(text):
	alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ "
	alphabet2 = "STUVWXYZABCDEFGHIJKLMNOPQR "
	cal = []
	for j in range(7):
		x = []
		for i in range(26):
			x.append(0)
		cal.append(x)
	text2 = ""
	for j in range(7):
        for i in range(j, len(text), 7):  # 2 3 4 5 6 7 8 9 10 ...#men ana caractere l 7ata win w logeur de cle q'on a terminer mel indice de coicidence
			cal[j][alphabet.index(text[i])] += 1
	return cal # return l'ensemble de 7  tableaux qui existe dans le tableau
	z = cryptanalyse(text2)
	for i in alphabet:
		print(i, end='\t')
		print()
	for i in z:
		for j in range(26):
			print(i[j], end="\t")
			print()
	for i in range(len(z)):
		print(alphabet[z[i].index(max(z[i])) - 4])

def vigener(txt, cle):# la fonction vigener: il va decheffrer le texte avec le mot cle q'on a trouver
	global alphabet
	txt = txt.replace(" ", "")
	lt = len(txt)
	lc = len(cle)
	txtclair = ""
	j = 0;
	for i in range(lt):
		poschartxt = alphabet.index(txt[i])
		poscharcle = alphabet.index(cle[j])
		pos = (poschartxt - poscharcle) % 26
		txtclair += alphabet[pos]
		j += 1
		if j == lc:
			j = 0
	print(txtclair)

print(polyalphabitiqueaveccalculindicecoicidence("ADLNE XDOYL SFYQQ BZEYF OQRLL AKLOW LLESS QBZOG VFQDL RYIWF OUTPI GQDSO KIUPS ZIZJU MGARG GWGFL SPIFX CBDOS PBIAI ZKLZT YAEXU GQAUD IHZHH NFUXQ GLRHM FQZHT QGKZC SOSMH BCZSQ HHGBL ADGKU HLCFY UQAVD GPDUF LCAQS AGLEP ISXIZ IQYUE DYOVI WEQVR DIOQG UOHEV IWMTS PDZQL EFGTG WWEDQ HFHLN FHHOC UTDSO QFSEE HLRTL RQRWQ GYEEW RGFJE EHHEA HCTMQ QGCID XXQZS EEXHX ZLSCY HXOWU UWVMB JEPIF MZJUX PHEHV CWEJQ CBEZG RDSSE DIVQO BLQTU AXLTQ WWBCY TQTDD ZHFAR GMHPO ZSSQB ZTMGN GBLOD KDZWZ AFMRZ BVNOS PYSYC UEOQE BIMTR GFIUF HHBFV MAYYA WYLQT UAXLT ATHZG AAOOD UBZIC YHPSW RAXHS SYEFH DURLR XIVPS CEXSS BSBRE IWFCB TQPDO CTMGR DGHLO BIQEH HCWHH ZCTBD IXESZ EZXUQ DYIEI VABAR QNRUB ALMJR ZRHTU SQADL NEXDO YWADQ LOSSL QWFUC URQXU AICEO EQABP CMPUQ ROAFW XESLN AZDZQ LAFXF UGJOP IOXVW INQBM VVOAV DOZLO DEQSS JLAYG IOATQ QFHAD ADILZ HLLOI VFIUL AKLOW LLXME DSKIE XUUPB EEIOA BSEEX HDALS PIOMZ PCQRF QOWAO LH"))
vigener(text2, "MOHAMED")
print(longeurdecle("ADLNE XDOYL SFYQQ BZEYF OQRLL AKLOW LLESS QBZOG VFQDL RYIWF OUTPI GQDSO KIUPS ZIZJU MGARG GWGFL SPIFX CBDOS PBIAI ZKLZT YAEXU GQAUD IHZHH NFUXQ GLRHM FQZHT QGKZC SOSMH BCZSQ HHGBL ADGKU HLCFY UQAVD GPDUF LCAQS AGLEP ISXIZ IQYUE DYOVI WEQVR DIOQG UOHEV IWMTS PDZQL EFGTG WWEDQ HFHLN FHHOC UTDSO QFSEE HLRTL RQRWQ GYEEW RGFJE EHHEA HCTMQ QGCID XXQZS EEXHX ZLSCY HXOWU UWVMB JEPIF MZJUX PHEHV CWEJQ CBEZG RDSSE DIVQO BLQTU AXLTQ WWBCY TQTDD ZHFAR GMHPO ZSSQB ZTMGN GBLOD KDZWZ AFMRZ BVNOS PYSYC UEOQE BIMTR GFIUF HHBFV MAYYA WYLQT UAXLT ATHZG AAOOD UBZIC YHPSW RAXHS SYEFH DURLR XIVPS CEXSS BSBRE IWFCB TQPDO CTMGR DGHLO BIQEH HCWHH ZCTBD IXESZ EZXUQ DYIEI VABAR QNRUB ALMJR ZRHTU SQADL NEXDO YWADQ LOSSL QWFUC URQXU AICEO EQABP CMPUQ ROAFW XESLN AZDZQ LAFXF UGJOP IOXVW INQBM VVOAV DOZLO DEQSS JLAYG IOATQ QFHAD ADILZ HLLOI VFIUL AKLOW LLXME DSKIE XUUPB EEIOA BSEEX HDALS PIOMZ PCQRF QOWAO LH"))
