#!/usr/bin/python3
def occurence(text):
	alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ "
	c=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
	for i in text:
		c[alphabet.index(i)]+=1
	return c
	
def polyalphabitiqueaveccalculindicecoicidence(text):
	alpha="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	text=text.replace(" ","")
	c=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
	for i in range(4, len(text), 7):
		c[alpha.index(text[i])] += 1
	n = 0
	ic = 0
	for i in range(len(c) - 1):
		n += c[i]
	for i in range(len(c) - 1):
		ic += (c[i] * (c[i] - 1)) / (n * (n - 1))
	return ic
	
def longeurdecle(text1):
	alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	text1 = text1.replace(" ", "")
	x = 1
	while (True):
		nbchar = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
		for i in range(0, len(text1), x):
			nbchar[alphabet.index(text1[i])] += 1
		n = 0
		for i in nbchar:
			n += i
		s = 0
		for i in range(len(nbchar)):
			s += (nbchar[i] * (nbchar[i] - 1)) / (n * (n - 1))
		if s > 0.06:
			return x
		else:
			x += 1
	
	
def CLE(z):
	alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	cle=""
	for i in range(len(z)):
		cle+=alphabet[z[i].index(max(z[i])) - 4]
	return cle
	
def vigener(txt, cle):# la fonction vigener: il va decheffrer le texte avec le mot cle q'on a trouver
	alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	txt = txt.replace(" ", "")
	lt = len(txt)
	lc = len(cle)
	txtclair = ""
	j = 0;
	for i in range(lt):
		poschartxt = alphabet.index(txt[i])
		poscharcle = alphabet.index(cle[j])
		pos = (poschartxt - poscharcle) % 26
		txtclair += alphabet[pos]
		j += 1
		if j == lc:
			j = 0
	print(txtclair)

	
def dechiffavecIndiceCoin(text, longCle):
	alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	text = text.replace(" ", "")
	cal = []
	for j in range(longCle):
		x = []
		for i in range(26):
			x.append(0)
		cal.append(x)
	for j in range(longCle):
		for i in range(j, len(text), longCle):
			cal[j][alphabet.index(text[i])] += 1
	return cal
    
def dechiffrementCryptAnalyse(text):
	x = occurence(text)
	somme = 0
	for i in range(len(x) - 1):
		somme += x[i]
	l = longeurdecle(text)
	z = dechiffavecIndiceCoin(text, l)
	cle1 = CLE(z)
	return(vigener(text,cle1))
	
#print(CLE(dechiffavecIndiceCoin("ADLNEXDOYLSFYQQBZEYFOQRLLAKLOWLLESSQBZOGVFQDLRYIWFOUTPIGQDSOKIUPSZIZJUMGARGGWGFLSPIFXCBDOSPBIAIZKLZTYAEXUGQAUDIHZHHNFUXQGLRHMFQZHTQGKZCSOSMHBCZSQHHGBLADGKUHLCFYUQAVDGPDUFLCAQSAGLEPISXIZIQYUEDYOVIWEQVRDIOQGUOHEVIWMTSPDZQLEFGTGWWEDQHFHLNFHHOCUTDSOQFSEEHLRTLRQRWQGYEEWRGFJEEHHEAHCTMQQGCIDXXQZSEEXHXZLSCYHXOWUUWVMBJEPIFMZJUXPHEHVCWEJQCBEZGRDSSEDIVQOBLQTUAXLTQWWBCYTQTDDZHFARGMHPOZSSQBZTMGNGBLODKDZWZAFMRZBVNOSPYSYCUEOQEBIMTRGFIUFHHBFVMAYYAWYLQTUAXLTATHZGAAOODUBZICYHPSWRAXHSSYEFHDURLRXIVPSCEXSSBSBREIWFCBTQPDOCTMGRDGHLOBIQEHHCWHHZCTBDIXESZEZXUQDYIEIVABARQNRUBALMJRZRHTUSQADLNEXDOYWADQLOSSLQWFUCURQXUAICEOEQABPCMPUQROAFWXESLNAZDZQLAFXFUGJOPIOXVWINQBMVVOAVDOZLODEQSSJLAYGIOATQQFHADADILZHLLOIVFIULAKLOWLLXMEDSKIEXUUPBEEIOABSEEXHDALSPIOMZPCQRFQOWAOLH"
#,7)))
print(dechiffrementCryptAnalyse("ADLNEXDOYLSFYQQBZEYFOQRLLAKLOWLLESSQBZOGVFQDLRYIWFOUTPIGQDSOKIUPSZIZJUMGARGGWGFLSPIFXCBDOSPBIAIZKLZTYAEXUGQAUDIHZHHNFUXQGLRHMFQZHTQGKZCSOSMHBCZSQHHGBLADGKUHLCFYUQAVDGPDUFLCAQSAGLEPISXIZIQYUEDYOVIWEQVRDIOQGUOHEVIWMTSPDZQLEFGTGWWEDQHFHLNFHHOCUTDSOQFSEEHLRTLRQRWQGYEEWRGFJEEHHEAHCTMQQGCIDXXQZSEEXHXZLSCYHXOWUUWVMBJEPIFMZJUXPHEHVCWEJQCBEZGRDSSEDIVQOBLQTUAXLTQWWBCYTQTDDZHFARGMHPOZSSQBZTMGNGBLODKDZWZAFMRZBVNOSPYSYCUEOQEBIMTRGFIUFHHBFVMAYYAWYLQTUAXLTATHZGAAOODUBZICYHPSWRAXHSSYEFHDURLRXIVPSCEXSSBSBREIWFCBTQPDOCTMGRDGHLOBIQEHHCWHHZCTBDIXESZEZXUQDYIEIVABARQNRUBALMJRZRHTUSQADLNEXDOYWADQLOSSLQWFUCURQXUAICEOEQABPCMPUQROAFWXESLNAZDZQLAFXFUGJOPIOXVWINQBMVVOAVDOZLODEQSSJLAYGIOATQQFHADADILZHLLOIVFIULAKLOWLLXMEDSKIEXUUPBEEIOABSEEXHDALSPIOMZPCQRFQOWAOLH"))
print(vigener("ADLNEXDOYLSFYQQBZEYFOQRLLAKLOWLLESSQBZOGVFQDLRYIWFOUTPIGQDSOKIUPSZIZJUMGARGGWGFLSPIFXCBDOSPBIAIZKLZTYAEXUGQAUDIHZHHNFUXQGLRHMFQZHTQGKZCSOSMHBCZSQHHGBLADGKUHLCFYUQAVDGPDUFLCAQSAGLEPISXIZIQYUEDYOVIWEQVRDIOQGUOHEVIWMTSPDZQLEFGTGWWEDQHFHLNFHHOCUTDSOQFSEEHLRTLRQRWQGYEEWRGFJEEHHEAHCTMQQGCIDXXQZSEEXHXZLSCYHXOWUUWVMBJEPIFMZJUXPHEHVCWEJQCBEZGRDSSEDIVQOBLQTUAXLTQWWBCYTQTDDZHFARGMHPOZSSQBZTMGNGBLODKDZWZAFMRZBVNOSPYSYCUEOQEBIMTRGFIUFHHBFVMAYYAWYLQTUAXLTATHZGAAOODUBZICYHPSWRAXHSSYEFHDURLRXIVPSCEXSSBSBREIWFCBTQPDOCTMGRDGHLOBIQEHHCWHHZCTBDIXESZEZXUQDYIEIVABARQNRUBALMJRZRHTUSQADLNEXDOYWADQLOSSLQWFUCURQXUAICEOEQABPCMPUQROAFWXESLNAZDZQLAFXFUGJOPIOXVWINQBMVVOAVDOZLODEQSSJLAYGIOATQQFHADADILZHLLOIVFIULAKLOWLLXMEDSKIEXUUPBEEIOABSEEXHDALSPIOMZPCQRFQOWAOLH","MOHAMED"))
